<a href="https://colab.research.google.com/github/SamRB-dev/AutonomousSystemsLab/blob/main/Lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 2: First Steps with Data in Python

## Learning objectives
After this notebook, you should be able to:
- distinguish between a single value, a list, and an array,
- describe a dataset using the terms sample, feature, and label,
- create simple NumPy arrays,
- inspect a small pandas table.

## Why this notebook?
Machine learning starts with data.
Before training a model, you must understand:
- how data is stored,
- how to inspect it,
- how to separate inputs and targets.

## References
1. NumPy documentation.  
2. pandas documentation.  
3. Jake VanderPlas, *Python Data Science Handbook*, chapters on NumPy and pandas.  
4. Aurélien Géron, *Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow*, introductory sections on datasets.

## Part 1: From single values to lists

Run the next cells and compare the outputs.

In [4]:
height = 1.82
print(height)

1.82


In [5]:
heights = [1.82, 1.75, 1.91, 1.68]
print(heights)

[1.82, 1.75, 1.91, 1.68]


### Task 2.1
Create your own list with four numerical values and print it.

In [6]:
my_list: list = [i for i in range(0, 5)]
print(my_list)

[0, 1, 2, 3, 4]


## Part 2: NumPy arrays

NumPy is a standard library for numerical work in Python.

In [7]:
import numpy as np

data = np.array([1, 2, 3, 4])
print(data)
print(type(data))

[1 2 3 4]
<class 'numpy.ndarray'>


The array stores several values in a structured numerical form.

Run the next cell.

In [8]:
print("Mean value:", np.mean(data))
print("Maximum value:", np.max(data))
print("Minimum value:", np.min(data))

Mean value: 2.5
Maximum value: 4
Minimum value: 1


### Task 2.2
Create a NumPy array called `temperatures` with five values.
Then compute:
- the mean,
- the maximum,
- the minimum.

In [15]:
temperatures = np.array([i for i in range(1,10)])
print(temperatures.mean())
print(temperatures.max())
print(temperatures.min())

5.0
9
1


## Part 3: A tiny dataset

In machine learning, a dataset often contains:
- **samples**: individual observations,
- **features**: measured properties,
- **labels**: desired outputs.

Example:
- sample: one student,
- features: study hours, attendance,
- label: passed exam or not.

In [10]:
X = np.array([
    [2, 1],
    [4, 1],
    [6, 0],
    [8, 1]
])

y = np.array([0, 0, 1, 1])

print("X =")
print(X)
print("y =")
print(y)

X =
[[2 1]
 [4 1]
 [6 0]
 [8 1]]
y =
[0 0 1 1]


In this example:
- each row in `X` is one sample,
- each column in `X` is one feature,
- `y` contains the labels.

### Task 2.3
Answer in your own words:
- How many samples are stored in `X`?
- How many features does each sample have?

In [16]:
len(X)

4

In [11]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (4, 2)
Shape of y: (4,)


`X.shape` returns `(number_of_samples, number_of_features)`.

### Task 2.4
Interpret the output of `X.shape`.

## Part 4: A first pandas table

pandas is useful for table-like data.

In [17]:
import pandas as pd

df = pd.DataFrame({
    "study_hours": [2, 4, 6, 8,5],
    "attendance": [1, 1, 0, 1, 6],
    "passed": [0, 0, 1, 1, 7]
})

df

,study_hours,attendance,passed
0,2,1,0
1,4,1,0
2,6,0,1
3,8,1,1
4,5,6,7


### Task 2.5
Add one more row to the table by modifying the dictionary values.

### Reflection
Why is a table often easier to read than a plain array?

## Part 5: Separating features and labels

In machine learning, inputs and targets are usually separated.

In [13]:
X_table = df[["study_hours", "attendance"]]
y_table = df["passed"]

print(X_table)
print()
print(y_table)

   study_hours  attendance
0            2           1
1            4           1
2            6           0
3            8           1

0    0
1    0
2    1
3    1
Name: passed, dtype: int64


### Task 2.6
Explain the difference between:
- `X_table`
- `y_table`

## Short summary

You have now worked with:
- lists,
- NumPy arrays,
- dataset shapes,
- pandas tables,
- features and labels.

These concepts are the basis for the first scikit-learn examples in the next notebooks.

## Suggested reading
- VanderPlas: chapters on NumPy and pandas
- Géron: introduction to datasets and training data